sudo: false
language: node_js
node_js:
  - "4.2.2"
  - "0.12"
script:
  - npm install -g bower karma
  - $CI_ACTION
env:
  matrix:
  - CI_ACTION="npm test"
  - CI_ACTION="npm lint"
  - CI_ACTION="npm static"
  - CI_ACTION="npm cordova"
